# Generated by Django 2.0.1 on 2018-02-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MushroomSpot',
            new_name='FieldPlot',
        ),
    ]
