# Generated by Django 2.0.1 on 2018-03-13 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180228_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldplot',
            name='picture',
        ),
    ]
