# Generated by Django 2.0.1 on 2018-03-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_fieldplot_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldplot',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fieldplot',
            name='title',
        ),
        migrations.AddField(
            model_name='fieldplot',
            name='_range',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldplot',
            name='acreage',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldplot',
            name='bed_configuration',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldplot',
            name='bed_count',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldplot',
            name='commodity',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldplot',
            name='grower',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldplot',
            name='lines_per_bed',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldplot',
            name='pca',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldplot',
            name='ranch',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldplot',
            name='section',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldplot',
            name='shipper',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldplot',
            name='township',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldplot',
            name='variety',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldplot',
            name='wet_date',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
    ]
