# Generated by Django 2.0.1 on 2018-01-27 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranch', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('township', models.CharField(max_length=100)),
                ('grower', models.CharField(max_length=100)),
                ('shipper', models.CharField(max_length=100)),
                ('pca', models.CharField(max_length=100)),
                ('wet_date', models.DateField()),
                ('commodity', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('crop_range', models.CharField(max_length=100)),
                ('acreage', models.IntegerField(max_length=100)),
                ('bed_count', models.IntegerField(max_length=100)),
                ('lines_per_bed', models.IntegerField(max_length=100)),
                ('bed_configuration', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
