# Generated by Django 2.0.1 on 2018-02-04 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(max_length=100)),
                ('_range', models.IntegerField(verbose_name='Range')),
                ('section', models.IntegerField()),
                ('township', models.CharField(max_length=100)),
                ('shipper', models.CharField(max_length=100)),
                ('pca', models.CharField(max_length=100, verbose_name='PCA')),
                ('wet_date', models.DateField()),
                ('commodity', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('acreage', models.IntegerField()),
                ('bed_count', models.IntegerField()),
                ('lines_per_bed', models.IntegerField()),
                ('bed_configuration', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ['state', 'city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter ranch name.', max_length=200, verbose_name='Ranch')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='grower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='view.Grower'),
        ),
        migrations.AddField(
            model_name='field',
            name='ranch',
            field=models.ManyToManyField(help_text='Select a Ranch for this field.', to='view.Ranch'),
        ),
        migrations.AddField(
            model_name='field',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
