# Generated by Django 2.0.1 on 2018-02-04 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0003_auto_20180203_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranch',
            options={'ordering': ['name', 'state', 'city']},
        ),
        migrations.AddField(
            model_name='ranch',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ranch',
            name='state',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.RemoveField(
            model_name='field',
            name='ranch',
        ),
        migrations.AddField(
            model_name='field',
            name='ranch',
            field=models.ForeignKey(default='', max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='view.Ranch'),
        ),
        migrations.AlterField(
            model_name='ranch',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
