# Generated by Django 2.0.1 on 2018-02-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0004_auto_20180203_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodity',
            options={'verbose_name_plural': 'Commodities'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['ranch', 'lot']},
        ),
        migrations.AlterModelOptions(
            name='grower',
            options={'ordering': ['state', 'name', 'city']},
        ),
        migrations.AlterModelOptions(
            name='pca',
            options={'ordering': ['state', 'name', 'city'], 'verbose_name_plural': 'PCAs'},
        ),
        migrations.AlterModelOptions(
            name='ranch',
            options={'ordering': ['state', 'name', 'city'], 'verbose_name_plural': 'Ranches'},
        ),
        migrations.AlterModelOptions(
            name='shipper',
            options={'ordering': ['state', 'name', 'city']},
        ),
    ]
